### ISSUE TITLE
Make packaged release

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/interface_guidelines#3]
Devise a packaging and release strategy for the theme that works for Maven based java application, possibly also node.js and other frameworks. Should provide (maybe as separate packages) both compiled CSS and LESS sources. Each release should have a unique version number. Usage as dependency should be strongly encouraged (as opposed to integrating a copy of the style sources in secondary projects).

**Comment by sanmai-NL** [comment]
Discussed today, work underway.

**Comment by sanmai-NL** [comment]
A [project](https://github.com/clarin-eric/base_style/tree/efdd6855644a134cb38aa8a481d9da30a2e3730d) that does this was set up. See [this release](https://github.com/clarin-eric/base_style/releases/tag/0.1.0) built via Travis CI. The release artifacts are put on GitHub whenever a tag is pushed.

@twagoo will enhance this further so that a [Maven](https://maven.apache.org/) artifact gets uploaded to the CLARIN Maven repo. See e.g. [this tutorial](https://coderwall.com/p/9b_lfq/deploying-maven-artifacts-from-travis). It appears creating a separate project and a Maven POM isn't needed, it can be done from the [existing project](https://github.com/clarin-eric/base_style).

I will work on decomposing the CLARIN website Drupal customizations into a Drupal Bootstrap subtheme, and make [that subtheme](https://github.com/clarin-eric/www-clarin-eu_src/tree/414cfdfa9f1f3956ec4f210ca4a82e6054ca38ba/sites/all/themes/CLARIN_Horizon) depend on [`base_style`](https://github.com/clarin-eric/base_style) using Travis CI, and without vendoring.

**Comment by twagoo** [comment]
CSS compilation and deployment to GitHub releases is now implemented in the [base_style](https://github.com/clarin-eric/base_style) repository. [Issue #4](https://github.com/clarin-eric/base_style/issues/4) of that repository covers Maven packaging.
